import type { SelfTryPlan } from "./SelfTryCard";

export const SELF_TRY_PLANS: SelfTryPlan[] = [
  {
    id: "starter",
    title: "СТАРТОВЫЙ",
    term: "СРОК 15-20",
    price: "120 000",
    conceptLabel: "Выбранная концепция:",
    conceptOptions: [
      { value: "drops", label: "Дроппы" },
      { value: "loft", label: "Loft" },
      { value: "minimal", label: "Minimal" },
    ],
    area: 50,
    areaMin: 30,
    areaMax: 120,
    sizeLabel: "Размер S",
    ctaLabel: "Оформить",
    features: [
      "Обмерный план",
      "Планировка с расстановкой мебели",
      "Плановый бюджет со спецификацией",
    ],
  },
  {
    id: "base",
    title: "БАЗОВЫЙ",
    term: "СРОК 25-30",
    price: "120 000",
    conceptLabel: "Выбранная концепция:",
    conceptOptions: [
      { value: "drops", label: "Дроппы" },
      { value: "loft", label: "Loft" },
      { value: "minimal", label: "Minimal" },
    ],
    area: 50,
    areaMin: 30,
    areaMax: 120,
    sizeLabel: "Размер S",
    ctaLabel: "Оформить",
    features: [
      "Обмерный план",
      "Планировка с расстановкой мебели",
      "План розеток",
      "План отделки",
      "План управления освещением",
      "План электрических розеток",
      "Коллажи с подбором материалов",
      "Плановый бюджет со спецификацией",
    ],
  },
  {
    id: "optimal",
    title: "ОПТИМАЛЬНЫЙ",
    term: "СРОК 1 МЕСЯЦ",
    price: "120 000",
    conceptLabel: "Выбранная концепция:",
    conceptOptions: [
      { value: "drops", label: "Дроппы" },
      { value: "loft", label: "Loft" },
      { value: "minimal", label: "Minimal" },
    ],
    area: 50,
    areaMin: 30,
    areaMax: 120,
    sizeLabel: "Размер S",
    ctaLabel: "Оформить",
    features: [
      "Обмерный план",
      "План демонтажа",
      "План монтажа",
      "План расстановки мебели",
      "План отделки стен",
      "План размещения сантехнического оборудования",
      "План напольного покрытия",
      "План потолочного покрытия",
      "План освещения",
      "План управления освещением",
      "План электрических розеток",
      "План дверных полотен и проемов",
      "Развертки стен ванной и кухни помещений",
      "Комплект с подбором материалов",
      "Плановый бюджет со спецификацией",
    ],
  },
];
